### ISSUE TITLE
%rsp-relative loads, stores, effective addresses

### ISSUE THREAD

**Issue by matsc-at-sics-se** [matsc-at-sics-se/unison#9]
I'm not sure where in the tool-chain this should go, but here are some initial thoughts.
This issue is strongly related to spilling.

From SU_init_alloc_mem.uni:
```
    o53: [t69] <- LEA64r [%stack.0,1,_,0,_]
    o58: [t79] <- MOV64rm [%stack.0,1,_,0,_] (mem: 5)
frame:
    %stack.0: offset = 0, size = 16, align = 8
```
Now pretend that the last line had read:
```
    %stack.0: offset = 32, size = 16, align = 8
```
Then somewhere the two operations should be transformed into:
```
    o53: [t69] <- LEA64r [%rsp,1,_,32,_]
    o58: [t79] <- MOV64rm [%rsp,1,_,32,_] (mem: 5)
```
Note that o53/t69 is in fact rematerializable, provided that %rsp does not change in the mean time.
That could depend on context and is related to ADJSTACKCALL* magic.

Finally, the "memory" part of the register array should roughly correspond to the stack frame, I guess.
